% registra a base de conhecimento para a arvore genealogica para a familia "Gerhardt"
pais(reinaldo, nilson).
pais(nilson, ines).
pais(nilson, ivonei).
pais(nilson, ivanete).
pais(nilson, ivanilde).
pais(nilson, elton).
pais(elton, simone).
pais(elton, robison).
pais(darci, willian).
pais(darci, weslei).
pais(redo, jony).
pais(redo, jackson).
pais(redo, jeferson).
pais(elza, nilson).
pais(bendolino, lira).
pais(lucina, lira).
pais(lira, ines).
pais(lira, ivanete).
pais(lira, ivonei).
pais(lira, ivanilde).
pais(lira, elton).
pais(ivanete, jony).
pais(ivanete, jackson).
pais(ivanete, jeferson).
pais(ivanilde, willian).
pais(ivanilde, weslei).
pais(vilce, simone).
pais(vilce, robson).
